### ISSUE TITLE
multiple channels not able to connect using the docker m3u

### ISSUE THREAD

**Issue by untitledlives** [chris102994/docker-toonamiaftermath#11]
VLC is unable to open the MRL 'http://api.toonamiaftermath.com:3000/snick-est/playlist.m3u8?useHttps=true'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://api.toonamiaftermath.com:3000/snick-est/playlist.m3u8?streamDelay=180&useHttps=true'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://api.toonamiaftermath.com:3000/mtv97/playlist.m3u8?useHttps=true'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'http://api.toonamiaftermath.com:3000/mtv97/playlist.m3u8?streamDelay=180&useHttps=true'. Check the log for details.

**Comment by untitledlives** [comment]
So found the issue, its odd but I have to load into TA web proper then everything loads locally VLC/ plex chrome and android apps.

perhaps it has to renew the cookie that has my login credentials. 

oddly still can not load on the plex for windows app.

**Comment by chris102994** [comment]
Login credentials/cookies have nothing to do with it. For instance I have no login - I just scraped these URLs from messing around in the web console. In fact there's 0 translation from your local cookies and Plex or I daresay VLC streaming it. 

In my case for instance I use Emby on a completely different server. Emby rebroadcasts the stream to the client using FFMpeg. I assume Plex has a similar structure. 

Their servers are known for going offline randomly so I'm guessing that either that happened or you had some networking hiccups.
