### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by enduser001** [chris102994/docker-toonamiaftermath#2]
Thank you for this, especially the schedule. Your work is appreciated.

**Comment by enduser001** [comment]
Found the URL for the episode descriptions
https://api.toonamiaftermath.com/mediainfo?name={}&episode={}

so you can pull the metadata from a URL like 
https://api.toonamiaftermath.com/mediainfo?name=Home%20Movies&episode=9

**Comment by chris102994** [comment]
That would be a cool addition. I really need to go back through this project and format it better + add some tests. When I created it I just kind of hacked it together. I will likely add this in the future if I ever get back around to doing that. Feel free to submit a PR if you want and I could add it that way too!

I'm glad someone else has found a use for it!

**Comment by chris102994** [comment]
I added this feature in the 2.0.0 reworking of Docker-TA. Read the updated README and enjoy.
