### ISSUE TITLE
Dummy schedule fails plex import

### ISSUE THREAD

**Issue by enduser001** [chris102994/docker-toonamiaftermath#3]
Love the update.
I originally tested with the first TA channel in Plex and it worked successfully, so I enabled all the channels using the provided TA dummy epg for movies and 97. Thats when I started having issues with the guide failing importing into plex. If I change the epg to use xTeve dummy epg for those two channels, it successfully loads into plex. 

I am under the impression that your dummy movie schedule is more accurate to TA to know at least the progress of a movie, even if we don't know whats playing. Is this true?

**Comment by chris102994** [comment]
Unfortunately I can not see the status of what's playing on those channels since they do not provide any schedules for them. The dummy channels weren't tested extensively (since I only use emby myself). The "dummy" was a simple 24 hour programme element so that I'd see the channel name on the guide (I personally hate the channel info unavailable messages). I will look at revising it into 30m or 1hr blocks.

**Comment by enduser001** [comment]
No worries, I do appreciate the work. The work around with the xTeve dummy epg is not a deal breaker and the work you have done on the schedule is sweet. Thank you.

**Comment by enduser001** [comment]
For episodes, i noticed that format is not correct. 
XMLTV Standard is the "xmltv_ns" numbering system. The format is.

    <episode-num system="xmltv_ns">2 . 9 . 0/1</episode-num>

Basically the full version is;
<episode-num system="xmltv_ns">Season{/Number of season in total} . Episode{/Number of Episodes in this season} . {Part number/Number of parts in this episode}</episode-num>

The only trick to the xmltv_ns format is that it starts counting from zero instead of one, so the 7th Episode of the 4th Season, when made as a one part episode would be "3 . 6 . 0/1".  I played with the epg xml manually with find and replace, reloaded it and I see now the schedule shows the episode title, season and serialized in plex. 

edit in line 285 of toonamiaftermath.py
 _episode_num = [EpisodeNum(content=['{} . {} . 0/1'.format(media_info_object.episode.season, media_info_object.episode.epNum)], system='xmltv_ns')]

I can't figure out how to -1 the seasons and episodes.

**Comment by chris102994** [comment]
Ah. I guess the article I found was a little misleading. This is a strange format. I will look at revising the logic to better support this. I appreciate you bringing these issues to my attention.

**Comment by chris102994** [comment]
I have fixed both of these issues in my latest 2 commits.
