### ISSUE TITLE
-p exit

### ISSUE THREAD

**Issue by jeffytheboy** [chris102994/docker-toonamiaftermath#5]
mkdir -p exits with 111 every time the container is run

**Comment by chris102994** [comment]
I need some more info.
From that vague description my first thought are that you don't have proper privelage to write to a docker mounted volume.
If you could post your Docker command and Log output from the command

**Comment by jeffytheboy** [comment]
Sorry about being vague. I didn't know what I needed to post to be more helpful. Here's the output and the command

sudo docker run docker.pkg.github.com/chris102994/docker-toonamiaftermath/docker-toonamiaftermath:ubuntu-18-latest -p 8000:8000 -v /toonami/config --restart unless-stopped
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 50-toonami-attrs: applying...
[fix-attrs.d] 50-toonami-attrs: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-users-and-groups: executing...
usermod: no changes
[cont-init.d] 01-users-and-groups: exited 0.
[cont-init.d] 05-init-mounted-folders: executing...
[05-init-mounted-folders]: First boot with mounted /config/data detected.
[05-init-mounted-folders]: First boot with mounted /config/log detected.
[cont-init.d] 05-init-mounted-folders: exited 0.
[cont-init.d] 10-display-container-info: executing...
[10-display-container-info]:
-------------------------
# USER DEFINED VARIABLES:
-------------------------
LC_ALL=C.UTF-8
GROUPNAME=user
USERNAME=user
PUID=900
FIRST_RUN=TRUE
PGID=900
-------------------------
# UID/GID of user:
-------------------------
UID: 900
GID: 900
-------------------------
# FOLDER PERMISSIONS:
-------------------------
drwxr-xr-x 1 user user 4096 Feb 25 23:58 /app
drwxr-xr-x 4 user user 4096 Mar 28 02:45 /config
drwxr-xr-x 1 user user 4096 Feb 25 23:58 /defaults
-------------------------
[cont-init.d] 10-display-container-info: exited 0.
[cont-init.d] 40-fix-toonami-attrs: executing...
[cont-init.d] 40-fix-toonami-attrs: exited 0.
[cont-init.d] 50-first-run: executing...
[cont-init.d] 50-first-run: exited 0.
[cont-init.d] 60-fix-nginx-config: executing...
Ensuring proper NGINX configuration.
[cont-init.d] 60-fix-nginx-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[run]: The Package Manager is apt-get
ifelse: fatal: unable to exec -p: No such file or directory
[cmd] -p exited 111
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by jeffytheboy** [comment]
I think I figured it out. For some reason the -v command isn't passing anything along to the container. I've tried -v /config and -v /home/Jeff/test:/config and for some reason it isn't doing anything
