### ISSUE TITLE
Channels disappearing?

### ISSUE THREAD

**Issue by thegdoubleodees** [chris102994/docker-toonamiaftermath#6]
I noticed channels disappearing from the guide restarting the container and scanning new channels seems to fix it.  Wondering if this is just the limitation of generating a new m3u file and letting plex know about the new file?

**Comment by thegdoubleodees** [comment]
This may be a per app issue, web doesn't seem to be affected.

**Comment by chris102994** [comment]
Hmm if you restart the container then neither the m3u or xmltv will be available until it's done with the first run. Other than that I don't use plex so I'm afraid I'm not much help on how their tv handling works.
