### ISSUE TITLE
docker-XUMO please?

### ISSUE THREAD

**Issue by CHJ85** [chris102994/docker-toonamiaftermath#8]
Hi there. Could you put together one of these for XUMO please?
I've been trying fHDHR but this one uses way too much memory and is constantly crashing. But your stuff works.
Maybe you can get something out of this source code: https://github.com/fHDHR/fHDHR_plugin_origin_XUMO.

**Comment by chris102994** [comment]
I don't have the time for that right now. You can feel free to use my code and put it together!

**Comment by CHJ85** [comment]
I'm not a programmer.
I would if I could.
But could you keep it mind for when you do have time and are willing to do some programming?
